# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [1]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [2]:
a = pd.Series([100,200,300,400])

Print a, and data type

In [3]:
print(a)
print(a.dtype)

0    100
1    200
2    300
3    400
dtype: int64
int64

Using indexing access the element 300 from the series a.

In [4]:
a[2]

np.int64(300)

What are the values of index for series a?

In [5]:
a

0    100
1    200
2    300
3    400
dtype: int64

Change the index to  ['c', 'a', 'b', 'd']

In [6]:
a.index = ['c', 'a', 'b', 'd']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [7]:
a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [8]:
a.sort_index(inplace=True)

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [9]:
b = pd.Series([800,450,100] , index = ['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [10]:
a = pd.concat([a, b])
print(a)

a    200
b    300
c    100
d    400
e    800
f    450
g    100
dtype: int64

In [11]:
#print a again after appending b into it
print(a)

a    200
b    300
c    100
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [12]:
sorted_a = a.sort_values(ascending=False)
print(sorted_a.index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [13]:
df = pd.DataFrame(a)
print(df)

     0
a  200
b  300
c  100
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [14]:
df.shape
print('It implies that dataframe has 7 rows and 1 column')

It implies that dataframe has 7 rows and 1 column

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [15]:
# yep its same as the series.
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [16]:
print(df.head())

     0
a  200
b  300
c  100
d  400
e  800

In [17]:
print(df.tail())

     0
c  100
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [18]:
df.columns = ['points']
df

   points
a     200
b     300
c     100
d     400
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [19]:
fruits = pd.Series(np.random.choice(['orange','mango','apple'], 7))
print(fruits)

0     mango
1    orange
2     mango
3     apple
4     apple
5     apple
6     mango
dtype: object

In [20]:
#Create fruits array
fruits = np.array(['orange','mango','apple'])

In [21]:
#Create series fruits out of fruits array
fruits = pd.Series(fruits)
print(fruits)

0    orange
1     mango
2     apple
dtype: object

Change the index of fruits to the index of dataframe df

In [22]:
print(fruits)
print(df)

0    orange
1     mango
2     apple
dtype: object
   points
a     200
b     300
c     100
d     400
e     800
f     450
g     100

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [39]:
d1 = pd.DataFrame({
    'city': ['Chandigarh' , 'Delhi' , 'Kanpur' , 'Chennai' , 'Manali'],
    'temperature': [15,22,20,26,-2]
})

Print(d1)

In [40]:
print(d1)

         city  temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [41]:
d1.shape

(5, 2)

Set city = d1['city']

In [42]:
city = d1['city']

print city <br>
What is the type of city.

In [43]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [44]:
d2 = pd.DataFrame({
    'city': ['Bengalaru','Coimbatore','Srirangam','Pondicherry'],
    'temperature': [24,35,36,39]
})

print the shape of this dataframe

In [45]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [46]:
d3 = pd.concat([d1,d2])

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [48]:
cities_le_20 = d3[d3['temperature'] <= 20]
print(cities_le_20)
print(f"Number of cities with temperature less than or equal to 20: {cities_le_20.shape[0]}")

         city  temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2
Number of cities with temperature less than or equal to 20: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [49]:
cities_ge_35 = d3[d3['temperature'] >= 35]
print(cities_ge_35)

          city  temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [50]:
def is_ut(city):
    union_territories = ['Chandigarh', 'Pondicherry', 'Delhi']
    return city in union_territories

d3['is_ut'] = d3['city'].apply(is_ut)

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [52]:
def c_to_f(celsius):
    return (celsius * 9/5) + 32

In [53]:
# check function c_to_f(10)
print(c_to_f(10))

50.0

In [54]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'
d3['temp_farenhiet'] = d3['temperature'].apply(c_to_f)

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [56]:
ut_cities_in_d1 = d1[d1['city'].apply(is_ut)]
print(ut_cities_in_d1)

         city  temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [57]:
cities_above_90F = d1[d1['temperature'].apply(c_to_f) > 90]
print(cities_above_90F)

Empty DataFrame
Columns: [city, temperature]
Index: []

Select only the first three rows of the dataframe d1.

In [59]:
d1.head(3)

         city  temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [60]:
print(d3.iloc[:, -2:])

   is_ut  temp_farenhiet
0   True            59.0
1   True            71.6
2  False            68.0
3  False            78.8
4  False            28.4
0  False            75.2
1  False            95.0
2  False            96.8
3   True           102.2

## Groupby

In [61]:
# Create a dataframe using dictionary of your choice
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [18, 19, 17, 18],
    'Marks': [95 , 90 , 85 , 92]
}
df_new = pd.DataFrame(data)
print(df_new)

      Name  Age  Marks
0    Alice   18     95
1      Bob   19     90
2  Charlie   17     85
3    David   18     92

In [62]:
# Use Groupby of single column with aggregate sum()
df_new.groupby('Name')['Marks'].sum()

Name
Alice      95
Bob        90
Charlie    85
David      92
Name: Marks, dtype: int64

In [63]:
# Use Groupby of single column with aggregate count()
df_new.groupby('Name')['Marks'].count()

Name
Alice      1
Bob        1
Charlie    1
David      1
Name: Marks, dtype: int64

In [64]:
# Use Groupby of single column with aggregate min() and max()
df_new.groupby('Name')['Marks'].agg(['min', 'max'])

         min  max
Name
Alice     95   95
Bob       90   90
Charlie   85   85
David     92   92

In [65]:
# Use Groupby of any 2 columns with aggregate mean()
df_new.groupby(['Name', 'Age'])['Marks'].mean()

Name     Age
Alice    18     95.0
Bob      19     90.0
Charlie  17     85.0
David    18     92.0
Name: Marks, dtype: float64

In [66]:
# Use Groupby of any 2 columns with aggregate min() and max()
df_new.groupby(['Name', 'Age'])['Marks'].agg(['min', 'max'])

             min  max
Name    Age
Alice   18    95   95
Bob     19    90   90
Charlie 17    85   85
David   18    92   92

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [67]:
a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [69]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [70]:
print(len(a))

457

What is the type of a?

In [73]:
type(a)

pandas.core.indexes.datetimes.DatetimeIndex